baseURL = "https://lokal.ninja/sachsen"
languageCode = "de-DE"
title = "Lokal Ninja - Sachsen"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Sachsen"
  repo = "sachsen"
