baseURL = "https://de.shoogle.net/sachsen"
languageCode = "de-DE"
title = "Sachsen"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "sachsen"
